CREATE TABLE [dbo].[Nota] (
    [ID] INT IDENTITY (1, 1) NOT NULL,
    [n1] NUMERIC (16, 2) NULL,
    [n2] NUMERIC (16, 2) NULL,
    [n3] NUMERIC (16, 2) NULL,
    [n4] NUMERIC (16, 2) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

